filter:
  paths:
    - modules/mongodb/*
    - modules/mongodb_watchdog/*
    - example.settings.local.php
  excluded_paths:
    - '*.html.twig'
checks:
  php:
    code_rating: true
    duplication: true
    fix_php_opening_tag: true
    remove_php_closing_tag: true
    one_class_per_file: true
    side_effects_or_types: true
    no_mixed_inline_html: true
    require_braces_around_control_structures: true
    php5_style_constructor: true
    no_global_keyword: false
    avoid_usage_of_logical_operators: true
    psr2_class_declaration: false
    no_underscore_prefix_in_properties: true
    no_underscore_prefix_in_methods: true
    blank_line_after_namespace_declaration: true
    single_namespace_per_use: true
    psr2_switch_declaration: false
    psr2_control_structure_declaration: false
    avoid_superglobals: false
    security_vulnerabilities: true
    no_exit: true
    use_self_instead_of_fqcn: true
    uppercase_constants: true
    simplify_boolean_return: true
    return_doc_comments: true
    return_doc_comment_if_not_inferrable: true
    remove_extra_empty_lines: true
    properties_in_camelcaps: true
    prefer_while_loop_over_for_loop: true
    parameter_doc_comments: true
    param_doc_comment_if_not_inferrable: true
    optional_parameters_at_the_end: true
    no_short_variable_names:
      minimum: '3'
    no_short_method_names:
      minimum: ''
    no_new_line_at_end_of_file: false
    no_long_variable_names:
      maximum: '20'
    no_goto: true
    newline_at_end_of_file: true
    more_specific_types_in_doc_comments: true
    fix_use_statements:
      remove_unused: true
      preserve_multiple: false
      preserve_blanklines: true
      order_alphabetically: true
    fix_line_ending: true
    parameters_in_camelcaps: true
    encourage_single_quotes: true
    encourage_postdec_operator: true
    coding_standard:
      name: Drupal
    classes_in_camel_caps: true
    avoid_unnecessary_concatenation: true
    avoid_perl_style_comments: true
    avoid_multiple_statements_on_same_line: true
    align_assignments: true
  javascript: { }

coding_style:
  php:
    indentation:
      general:
        use_tabs: false
        size: 2
      switch:
        indent_case: true
    spaces:
      general:
        linefeed_character: newline
      before_parentheses:
        function_declaration: false
        closure_definition: true
        function_call: false
        if: true
        for: true
        while: true
        switch: true
        catch: true
        array_initializer: false
      around_operators:
        assignment: true
        logical: true
        equality: true
        relational: true
        bitwise: true
        additive: true
        multiplicative: true
        shift: true
        unary_additive: false
        concatenation: true
        negation: false
      before_left_brace:
        class: true
        function: true
        if: true
        else: true
        for: true
        while: true
        do: true
        switch: true
        try: true
        catch: true
        finally: true
      before_keywords:
        else: true
        while: true
        catch: true
        finally: true
      within:
        brackets: false
        array_initializer: false
        grouping: false
        function_call: false
        function_declaration: false
        if: false
        for: false
        while: false
        switch: false
        catch: false
        type_cast: false
      ternary_operator:
        before_condition: true
        after_condition: true
        before_alternative: true
        after_alternative: true
        in_short_version: false
      other:
        before_comma: false
        after_comma: true
        before_semicolon: false
        after_semicolon: true
        after_type_cast: true
    braces:
      classes_functions:
        class: undefined
        function: undefined
        closure: undefined
      if:
        opening: undefined
        always: true
        else_on_new_line: true
      for:
        opening: undefined
        always: true
      while:
        opening: undefined
        always: true
      do_while:
        opening: undefined
        always: true
        while_on_new_line: false
      switch:
        opening: undefined
      try:
        opening: undefined
        catch_on_new_line: true
        finally_on_new_line: true
    upper_lower_casing:
      keywords:
        general: undefined
      constants:
        true_false_null: undefined

build:
  nodes:
    analysis:
      dependencies:
        after:
          - composer config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          - composer require --dev squizlabs/php_codesniffer:^3.6 drupal/coder:^8.3
      tests:
        override:
          - command: php-scrutinizer-run
            use_website_config: false
