<?php

/**
 * Implement hook_help().
 */
function mongodb_help($path, $arg) {
  switch ($path) {
    case 'admin/help#mongodb':
      return '<p>' . t('<a href="!project">MongoDB</a> implements a generic <a href="!mongo">MongoDB</a> interface.',
        array(
          '!project' => 'http://drupal.org/project/mongodb',
          '!mongo' => 'http://www.mongodb.org/',
        ));
      break;
  }
}

/**
 * Returns a the mongodb watchdog collection.
 */
function mongodb_collection($collection_name) {
  global $db_prefix;
  static $mongo, $collections, $simpletest_prefix;
  // We call this function earlier than the database is initalized so we would
  // read the parent collection without this.
  if (!isset($simpletest_prefix)) {
    if (isset($_SERVER['HTTP_USER_AGENT']) && preg_match("/^(simpletest\d+);/", $_SERVER['HTTP_USER_AGENT'], $matches)) {
      $simpletest_prefix = $matches[1];
    }
    else {
      $simpletest_prefix = '';
    }
  }
  // However, once $db_prefix is filled by the database, the simpletest_prefix
  // is no longer needed.
  if ($simpletest_prefix && $db_prefix && strpos($db_prefix, $simpletest_prefix) !== FALSE) {
    $simpletest_prefix = '';
  }
  $collection_name = $db_prefix . $simpletest_prefix . $collection_name;
  if (!isset($mongo)) {
    $server_name  = variable_get('mongodb_connection', 'localhost');
    $db_name = variable_get('mongodb_dbname', 'drupal');
    $mongo = new Mongo($server_name);
    $mongo = $mongo->selectDB($db_name);
  }
  if (!isset($collections[$collection_name])) {
    $collections[$collection_name] = $mongo->selectCollection($collection_name);
  }
  return $collections[$collection_name];
}

function mongodb_test_group_finished() {
  $db = mongodb_collection('cache')->db;
  foreach ($db->listCollections() as $collection) {
    if (preg_match('/\.simpletest\d+/', $collection)) {
      $db->dropCollection($collection);
    }
  }
}
