<?php

/**
 * Implement hook_requirements().
 */
function mongodb_requirements($phase) {
  $requirements = array();

  if (!extension_loaded('mongo')) {
    $requirements['mongodb'] = array(
      'title' => $t('Mongodb'),
      'value' => $t('Not found'),
      'description' => t('Mongodb requires the PHP MongoDB extension to be installed.'),
      'severity' => REQUIREMENT_ERROR,
    );
  }
  return $requirements;
}
