<?php

/**
 * @file
 *   Provide test mongodb_block_uis.
 */

/**
 * Implements hook_mongodb_block_ui_info().
 */
function mongodb_block_ui_test_mongodb_block_ui_info() {
  $mongodb_block_uis['test_cache'] = array(
    'info' => t('Test mongodb_block_ui caching'),
  );
  return $mongodb_block_uis;
}

/**
 * Implements hook_mongodb_block_ui_view().
 */
function mongodb_block_ui_test_mongodb_block_ui_view($delta = 0) {
  return array('content' => variable_get('mongodb_block_ui_test_content', ''));
}
