<?php

function mongodb_migrate_load_helper($entity_type, $entities, $age, &$fields, $options) {
  $all_bundles = variable_get('mongodb_migrate_bundles', array());
  $migrate_fields = variable_get('mongodb_migrate_fields', array());
  if (defined('DRUSH_VERSION') && $age == FIELD_LOAD_CURRENT && isset($all_bundles[$entity_type])) {
    $field_info = field_info_field_by_ids();
    $sql_fields = array();
    foreach ($fields as $field_id => $ids) {
      $field_name = $field_info[$field_id]['field_name'];
      if (isset($migrate_fields[$field_name])) {
        $sql_fields[$field_id] = $ids;
        unset($fields[$field_id]);
      }
    }
    if ($sql_fields) {
      field_sql_storage_field_storage_load($entity_type, $entities, $age, $sql_fields, $options);
    }
  }
}

function mongodb_migrate_write_helper($entity_type, $entity_id) {
  $migrate_fields = variable_get('mongodb_migrate_fields', array());
  foreach ($migrate_fields as $field_name => $v) {
    $field = field_info_field($field_name);
    db_update(_field_sql_storage_tablename($field))
      ->fields(array('deleted' => 2))
      ->condition('entity_type', $entity_type)
      ->condition('entity_id', $entity_id)
      ->execute();
  }
}
